services:
  - type: web
    name: servicio-social
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:6DdvRBwyYP8I05XoGcgiOixbIre7JQsY0KYXUsHcIjw=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://servicio-social.onrender.com
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: es
      - key: APP_FAKER_LOCALE
        value: es_MX
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.aftejfsurgmvvsklkftr.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: cemalu082316
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: BROADCAST_CONNECTION
        value: log
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel